apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*

build:
  #  local:
  #  push: false
  googleCloudBuild:
    projectId: automatic-tea-316711
  artifacts:
    - image: us.gcr.io/automatic-tea-316711/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/**/*.ts"
    - image: us.gcr.io/automatic-tea-316711/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "**/*.js"
    - image: us.gcr.io/automatic-tea-316711/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/**/*.ts"
    - image: us.gcr.io/automatic-tea-316711/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/**/*.ts"
    - image: us.gcr.io/automatic-tea-316711/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/**/*.ts"
